### ISSUE TITLE
Unnable to spawn an inbound car

### ISSUE THREAD

**Issue by medinarj** [HumanTree92/esx_advancedgarage#185] opened 2020-09-30 17:21 UTC
I am having troubles while I'm trying to pull out a dissapear/explote car, I've already activated car bounds and all stuff instead of the Jobs garages and bounds, I've applied the fixes in the DB and all that stuff.

The only way to get it back it's deleting the car,
If my car is out, in the spawn menú appears as if the car is in the inbound but if I go to inbound, it is not there.

So Please help me to fix it, if you need more information ask me.

Tranks

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: NO
Have you looked through the Closed Topics?: YES
Have you looked through the Wiki?: YES
Are you using a Pre-Installed ESX? If Yes who?: NO
Are you using es_extended? If Yes what Version? (Example: 1.2): Yes, 1.2
Are you using Essentialmode?: NO
Are you using ExtendedMode?: NO
Are you using OneSync?: NO
Linux or Windows?: Windows

![sql1](https://user-images.githubusercontent.com/72157527/94718161-a3c89d00-0351-11eb-9cf7-8e30781a7443.PNG)
![sql2](https://user-images.githubusercontent.com/72157527/94718168-a75c2400-0351-11eb-843a-9af25af3a786.PNG)
![config](https://user-images.githubusercontent.com/72157527/94718068-74199500-0351-11eb-8a4b-92c8c5a830f3.PNG)
![ifcarisout](https://user-images.githubusercontent.com/72157527/94719306-49304080-0353-11eb-8ee4-2ca0e3f7367a.PNG)
![inbound](https://user-images.githubusercontent.com/72157527/94719525-914f6300-0353-11eb-9157-a82b553676c4.PNG)

**Comment by HumanTree92** [comment] 2020-10-03 09:37
Duplicate of https://github.com/HumanTree92/esx_advancedgarage/issues/182

**Closed by HumanTree92** 2020-10-03 09:37 UTC
Labels: Bug
